// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXfoPKD7hVwOECuMZXkwsNfeJsUdZ2B_U',
    appId: '1:370194961915:web:6e5bdde34e68a76596a75e',
    messagingSenderId: '370194961915',
    projectId: 'enjoy-family-resturant',
    authDomain: 'enjoy-family-resturant.firebaseapp.com',
    storageBucket: 'enjoy-family-resturant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3z_vi4otuWcOsXqvTFg8rk5BVDi2LYuM',
    appId: '1:370194961915:android:ad0db85746017fb096a75e',
    messagingSenderId: '370194961915',
    projectId: 'enjoy-family-resturant',
    storageBucket: 'enjoy-family-resturant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArmofQLTfbpcmocM2kaTrEebzC_5mpEY4',
    appId: '1:370194961915:ios:402370c7248ef76196a75e',
    messagingSenderId: '370194961915',
    projectId: 'enjoy-family-resturant',
    storageBucket: 'enjoy-family-resturant.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );
}
